### ISSUE TITLE
Exposed API Keys

### ISSUE THREAD

**Issue by mariannerv** [manascb1344/TensorForce#63]
Hello! Not sure if it is intentional but your API keys are exposed which poses significant security risks. Probably best to create a .env file to store those in. If it is intentional ignore this :)

**Comment by manascb1344** [comment]
Hey! Thanks for the heads-up! It wasn't intentional. You're absolutely free to send a PR if you'd like, much appreciated! 😊

**Comment by mariannerv** [comment]
I'd love to!
